<a href="https://colab.research.google.com/github/vsrnitp/Emotion-Recognition-Dataset/blob/main/RUDRA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#writing down the API key for Custom google search...
api_key = "*********"

In [ ]:
#installing the google API fro python client....
pip install google-api-python-client

In [10]:
from apiclient.discovery import build

In [13]:
#initiate customSearch resource....
resource = build("customsearch",'v1',developerKey=api_key).cse()

In [ ]:
type(resource)

In [21]:
#Executing search by passing search query....
result = resource.list(q='elon-musk',cx='5b33ce03fbaac6118').execute()

In [ ]:
#looping through the search results....
for item in result['items']:
  print(item['title'])
  print(item['htmlSnippet'])
  print(item['link'])
  print("\n")
  print("\n")


In [43]:
#searching images....
img_result = resource.list(q='elon-musk',cx='5b33ce03fbaac6118',searchType='image').execute()

In [ ]:
img_result

**Implementing the ML model for EMOTION RECOGNITION based on Text**






In [2]:
#importing Pandas for data analysis and manipulation......
import pandas as pd

In [3]:
#importing test dataset.... [using separator(sep) for separating the data afte encountering semicolon(;)]
test_dataset_url = 'https://raw.githubusercontent.com/vsrnitp/Emotion-Recognition-Dataset/main/test.txt'
test_dataset = pd.read_csv(test_dataset_url,sep=";",header=None)


In [4]:
test_dataset.head()

0        1
0  im feeling rather rotten so im not very ambiti...  sadness
1          im updating my blog because i feel shitty  sadness
2  i never make her separate from me because i do...  sadness
3  i left with my bouquet of red and yellow tulip...      joy
4    i was feeling a little vain when i did this one  sadness

In [5]:
#importing train dataset....
train_dataset_url = 'https://raw.githubusercontent.com/vsrnitp/Emotion-Recognition-Dataset/main/train.txt'
train_dataset = pd.read_csv(train_dataset_url,sep=";",header=None)

In [6]:
train_dataset.head()

0        1
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [7]:
#importing validation dataset.....
val_dataset_url = 'https://raw.githubusercontent.com/vsrnitp/Emotion-Recognition-Dataset/main/val.txt'
val_dataset = pd.read_csv(val_dataset_url,sep=";",header=None)

In [8]:
val_dataset.head()

0        1
0  im feeling quite sad and sorry for myself but ...  sadness
1  i feel like i am still looking at a blank canv...  sadness
2                     i feel like a faithful servant     love
3                  i am just feeling cranky and blue    anger
4  i can have for a treat or if i am feeling festive      joy

In [9]:
#importing numpy for linear algebra applications...
import numpy as np
#seeing the info...
test_dataset.info()
train_dataset.info()
val_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       2000 non-null   object
 1   1       2000 non-null   object
dtypes: object(2)
memory usage: 31.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       16000 non-null  object
 1   1       16000 non-null  object
dtypes: object(2)
memory usage: 250.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       2000 non-null   object
 1   1       2000 non-null   object
dtypes: object(2)
memory usage: 31.4+ KB


In [10]:
# Splitting X and Y [aka statement and emotion] and getting the number of data that we have....
x_train = train_dataset.iloc[:,0] 
y_train = train_dataset.iloc[:,1] 

x_test = test_dataset.iloc[:,0] 
y_test = test_dataset.iloc[:,1] 

x_val = val_dataset.iloc[:,0] 
y_val = val_dataset.iloc[:,1] 

x_train,y_train = np.array(x_train),np.array(y_train)
x_test,y_test = np.array(x_test),np.array(y_test)
x_val,y_val = np.array(x_val),np.array(y_val)

print(x_train.shape,"|",y_train.shape)
print(x_test.shape,"|",y_test.shape)
print(x_val.shape,"|",y_val.shape)

(16000,) | (16000,)
(2000,) | (2000,)
(2000,) | (2000,)


In [11]:
#Now converting Y (i.e - emotions) to integers.... [We have only five emotions over here]
#Also encoding the emotions using label Encoder....
print(train_dataset.iloc[:,1].value_counts())

int_y_train = []
int_y_test = []
int_y_val = []

for l in y_train:
    
    if l == "joy":        
        int_y_train.append(0)
        
    if l == "sadness":       
        int_y_train.append(1)            
    if l == "anger":      
        int_y_train.append(2)      
    if l == "fear":
        int_y_train.append(3)
    if l == "love":
        int_y_train.append(4)
    if l == "surprise":
        int_y_train.append(5)
        
        
for l in y_test:
    
    if l == "joy":        
        int_y_test.append(0)
        
    if l == "sadness":       
        int_y_test.append(1)            
    if l == "anger":      
        int_y_test.append(2)      
    if l == "fear":
        int_y_test.append(3)
    if l == "love":
        int_y_test.append(4)
    if l == "surprise":
        int_y_test.append(5)
        
for l in y_val:
    
    if l == "joy":        
        int_y_val.append(0)
        
    if l == "sadness":       
        int_y_val.append(1)            
    if l == "anger":      
        int_y_val.append(2)      
    if l == "fear":
        int_y_val.append(3)
    if l == "love":
        int_y_val.append(4)
    if l == "surprise":
        int_y_val.append(5)
        


        
int_y_train,int_y_test,int_y_val = np.array(int_y_train),np.array(int_y_test),np.array(int_y_val)
from sklearn import preprocessing
from keras.utils import np_utils

le = preprocessing.LabelEncoder()
le.fit(int_y_train)

encoded_y_train = le.transform(int_y_train)
encoded_y_test = le.transform(int_y_test)
encoded_y_val = le.transform(int_y_val)

encoded_y_train = np_utils.to_categorical(encoded_y_train)
encoded_y_test = np_utils.to_categorical(encoded_y_test)
encoded_y_val = np_utils.to_categorical(encoded_y_val)

#Here we are checking the emotions after getting encoded....
print(encoded_y_test)

#printing the label encoded value upto 10th row....
print(int_y_test[:10])

joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: 1, dtype: int64
[[0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
[1 1 1 0 1 3 2 0 0 2]


In [12]:
#importing nltk...
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [13]:
#Peforming Tokenization , padding and sequesting...
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences
from nltk.corpus import stopwords

stopwords = stopwords.words('english')

x_train_cl = []
x_test_cl = []
x_val_cl = []


# Deleting stopwords
for text in x_train:
    
    text = text.split()
    text = [word for word in text if word not in stopwords]
    text = " ".join(text)
    x_train_cl.append(text)
    
for text in x_test:
    
    text = text.split()
    text = [word for word in text if word not in stopwords]
    text = " ".join(text)
    x_test_cl.append(text)

for text in x_val:
    
    text = text.split()
    text = [word for word in text if word not in stopwords]
    text = " ".join(text)
    x_val_cl.append(text)
    
x_train,x_test,x_val = np.array(x_train_cl),np.array(x_test_cl),np.array(x_val_cl)

# We use total_text for fitting tokenizer in general 
total_text = np.concatenate((x_train,x_test,x_val),axis=0)

num_words = 2000

tokenizer = Tokenizer(num_words = num_words) 

tokenizer.fit_on_texts(total_text)

list(tokenizer.word_index)[:10]

['feel',
 'feeling',
 'like',
 'im',
 'really',
 'know',
 'time',
 'little',
 'get',
 'people']

In [14]:
#Now we will tokenize everything.....
x_train_token = tokenizer.texts_to_sequences(x_train)
x_test_token = tokenizer.texts_to_sequences(x_test)
x_val_token = tokenizer.texts_to_sequences(x_val)

total_token = np.concatenate((x_train_token,x_test_token,x_val_token),axis=0)

<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


In [15]:
# Padding (Getting the mean length of the text....)
print(np.mean([len(text) for text in total_token]))

7.65465


In [16]:
#Using 20 as padding....
x_train_pad = pad_sequences(x_train_token,20) 
x_test_pad = pad_sequences(x_test_token,20)
x_val_pad = pad_sequences(x_val_token,20)

print(x_train_pad[0],end="\n-------------------------------------------------------------------------\n")
print(x_train_pad[1])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  50
   1 510]
-------------------------------------------------------------------------
[   0    0    0    0    0    0    0    0    0    0    0    0   31    2
  409  432   44   54 1565 1252]


In [17]:
#Now building a simple RNN model.....
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense,CuDNNGRU,Embedding,Bidirectional


model = Sequential()

model.add(Embedding(input_dim=2000
                   ,output_dim=100
                   ,input_length=20))

model.add(Bidirectional(CuDNNGRU(units=16,return_sequences=True)))

model.add(Bidirectional(CuDNNGRU(units=8)))

model.add(Dense(6,activation="softmax"))

model.compile(loss="categorical_crossentropy",optimizer="rmsprop",metrics=["accuracy"])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 100)           200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 20, 32)            11328     
_________________________________________________________________
bidirectional_1 (Bidirection (None, 16)                2016      
_________________________________________________________________
dense (Dense)                (None, 6)                 102       
Total params: 213,446
Trainable params: 213,446
Non-trainable params: 0
_________________________________________________________________


In [18]:
#fitting the data and running epochs...
print(x_train_pad.shape)
print(y_train.shape)
model.fit(x_train_pad,encoded_y_train,epochs=10,batch_size=20)

(16000, 20)
(16000,)
Epoch 1/10
800/800 [==============================] - 19s 9ms/step - loss: 1.3409 - accuracy: 0.4813
Epoch 2/10
800/800 [==============================] - 7s 9ms/step - loss: 0.4745 - accuracy: 0.8506
Epoch 3/10
800/800 [==============================] - 7s 9ms/step - loss: 0.2765 - accuracy: 0.9100
Epoch 4/10
800/800 [==============================] - 7s 9ms/step - loss: 0.2045 - accuracy: 0.9257
Epoch 5/10
800/800 [==============================] - 7s 9ms/step - loss: 0.1639 - accuracy: 0.9366
Epoch 6/10
800/800 [==============================] - 7s 9ms/step - loss: 0.1417 - accuracy: 0.9443
Epoch 7/10
800/800 [==============================] - 7s 9ms/step - loss: 0.1267 - accuracy: 0.9514
Epoch 8/10
800/800 [==============================] - 7s 9ms/step - loss: 0.1157 - accuracy: 0.9543
Epoch 9/10
800/800 [==============================] - 7s 9ms/step - loss: 0.1214 - accuracy: 0.9536
Epoch 10/10
800/800 [==============================] - 7s 9ms/step - loss: 0.1

In [19]:
#Now printing the accuracy score...
preds = model.predict_classes(x_test_pad)
from sklearn.metrics import accuracy_score

accuracy_score(preds,int_y_test)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


0.9185

In [73]:
#Now using the model to predict emotion for a sentence....

#firstly receiving the input that needs to be analyzed....
input = ['I was shocked to see him in the office']
#tokenizing the input.....
tokenized_input = tokenizer.texts_to_sequences(input)
#padding the input.....
padded_input = pad_sequences(tokenized_input,20)
#print(padded_input)
#predicting the output emotion class....
predicted_emotion_class = model.predict_classes(padded_input)
#converting the segmented class codes to emotions.....
predicted_emotion = "null"
for emotions in predicted_emotion_class:
  if emotions==0:
    #print("Joyful")
    predicted_emotion = "Joyful"
  if emotions==1:
    #print("Sad")
    predicted_emotion = "Sad"
  if emotions==2:
    #print("Angry")
    predicted_emotion = "Angry"
  if emotions==3:
    #print("Fearful")
    predicted_emotion = "Fearful"
  if emotions==4:
    #print("In Love")
    predicted_emotion = "In Love"
  if emotions==5:
    #print("Surprised")
    predicted_emotion = "Surprised"

print(predicted_emotion)
 


Surprised


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '
